### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by syedusama5556** [ArchieMeng/ncnn-android-waifu2x-demo#1]
sir can you update the code to support a higher scale as no scale above 2x seems to be implemented can you do it like this app

support needed scale > x4 x8 x16 etc.
support for model 
[Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan)  

[Real-CUGAN](https://github.com/nihui/realcugan-ncnn-vulkan)

https://play.google.com/store/apps/details?id=pro.archiemeng.waifu2x

**Comment by ArchieMeng** [comment]
It's just a demo project which means it will only support 2x by default. You can change it if you want.

**Comment by syedusama5556** [comment]
yes i tried 3x and 4x but the app crashes would be better if you could just update some of the code to fix the issue kindly

**Comment by syedusama5556** [comment]
sir still waiting your update
