### ISSUE TITLE
Error: x + width must be <= bitmap.width()

### ISSUE THREAD

**Issue by syedusama5556** [ArchieMeng/ncnn-android-waifu2x-demo#2]
`2023-01-08 15:41:46.937 4973-5022/pro.archiemeng.waifu2x E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: pro.archiemeng.waifu2x, PID: 4973
    java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
        at android.graphics.Bitmap.checkPixelsAccess(Bitmap.java:2022)
        at android.graphics.Bitmap.setPixels(Bitmap.java:2096)
        at pro.archiemeng.waifu2x.MainActivity.processBitmap(MainActivity.kt:351)
        at pro.archiemeng.waifu2x.MainActivity.access$processBitmap(MainActivity.kt:40)
        at pro.archiemeng.waifu2x.MainActivity$onCreate$4$1$1.invokeSuspend(MainActivity.kt:166)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d58a564, Dispatchers.Default]`

when i increase the scale to 3x or 4x it gives this issue and crashes. kindly update the code

**Comment by ArchieMeng** [comment]
Although I really want to help you with that which is already fixed in Waifu2x ncnn, I can't update the code for your case. I can assist you with fixing the bug later if I am free for this.

**Comment by syedusama5556** [comment]
sir i have emailed you and given you collaboration access to my code, all the jni stuff is done just have issue when I change the scale if you could just guide me what exactly i need to do i can do it also in my code i have added realcugan also but it has same issue 2 when i use a 4x model the app crashes or sometime gives destorted image.  this is my email if you could just guide me it would be a lot of help syedusama12345@gmail.com

**Comment by ArchieMeng** [comment]
Sorry, this is out of the scope of this project. I will close this issue.

**Comment by syedusama5556** [comment]
ok sir but if you could just solve this issue 

`  java.lang.IllegalArgumentException: x + width must be <= bitmap.width()`

> this issue comes in this section of the code when the scale is increased to 3x or 4x


           for (y in 0 until bitmapInput.height step upscaler.tileSize) {

            val height =
                min(bitmapInput.height - y, upscaler.tileSize)
            for (x in 0 until bitmapInput.width step upscaler.tileSize) {
                val width = min(bitmapInput.width - x, upscaler.tileSize)
                var tileBitmap = Bitmap.createBitmap(
                    bitmapInput,
                    x, y,
                    width, height
                )
                tileBitmap = upscaler.process(tileBitmap)
                bitmapOutput.setPixels(
                    tileBitmap.toInts(),
                    0, tileBitmap.width,
                    x * upscaler.scale, y * upscaler.scale,
                    tileBitmap.width, tileBitmap.height
                )
                val currentResult = Bitmap.createBitmap(
                    bitmapOutput,
                    0, 0,
                    bitmapOutput.width, (y + height) * upscaler.scale
                )
                lastImageViewCoroutine = lastImageViewCoroutine?.apply {
                    if (!this.isActive)
                        coroutineScope.launch { showBitmapImage(currentResult) }
                } ?: coroutineScope.launch { showBitmapImage(currentResult) }
            }
        }

**Comment by ArchieMeng** [comment]
```kotlin
            bitmapOutput.setPixels(
                tileBitmap.toInts(),
                0, tileBitmap.width,
                x * upscaler.scale, y * upscaler.scale,
                tileBitmap.width, tileBitmap.height
            )
```
Was bitmapOutput set to the correct size? I suggest setting a breakpoint to check the size of both bitmapOutput and tileBitmap. And check the variable x, y, upscaler.scale too. Hope this information helps.

**Comment by syedusama5556** [comment]
thanks i found the issue it was in the process function, i fixed that but, now there's another issue no matter which model i use realesrgan or cugan with 2x or 3x or 4x scale the image pixel don't increase above 1080px width what could be the cause i also checked the JNI function too and logged the dimensions of each tiles its giving correct result but the final output image don't get bigger then 1080px. you are a collaborator in the code if you could spare some time and check it out i would be very great full
